from langchain_groq import ChatGroq # type: ignore
from langchain.prompts import PromptTemplate# type: ignore
from langchain.schema.output_parser import StrOutputParser# type: ignore
from langchain.schema.runnable import RunnablePassthrough # type: ignore
from config import config

# Initialize Groq model with API key
groq_chat = ChatGroq(groq_api_key=config.GROQ_API_KEY, model_name=config.MODEL_NAME)

def format_docs(docs):
    """
    Formats the documents into a single string for context.

    Parameters:
    docs (list): A list of document objects. Each document object should have a 'page_content' attribute.

    Returns:
    str: A string containing the concatenated 'page_content' of all documents, separated by newlines.
    """
    return "\n\n".join(doc.page_content for doc in docs)

def run_chain(prompt_template, inputs):
    """
    Runs the prompt chain with the given prompt template and inputs.

    Parameters:
    prompt_template (PromptTemplate): A prompt template object that defines the structure and content of the prompt.
    inputs (dict): A dictionary containing the inputs for the prompt template, such as context and question.

    Returns:
    str: The output generated by the prompt chain, parsed as a string.
    """
    chain = RunnablePassthrough() | prompt_template | groq_chat | StrOutputParser()
    return chain.invoke(inputs)

# Define prompt templates
def get_prompt_template(use_case):
    if use_case == "generation":
        return PromptTemplate(
            input_variables=["context", "question"],
            template="""
            <s> [INST] You are an expert assistant providing detailed information specifically about Vishwakarma Institute of Technology (VIT), Pune. 
            Please ensure that your response follows these rules:

            Guidelines:
            1. Do not provide information about any institutions other than VIT Pune (e.g., Pune Institue of Technology).
            2. If asked about unavailable departments or engineering (e.g., Electrical Engineering), clearly mention that they are not offered at VIT Pune.
            3. Always base your responses on the provided documents. If the documents lack relevant information, politely inform the user that the information is not available at VIT Pune.
            4. Your response should be at least 20 words long.
            5. Highlight relevant VIT Pune departments, courses, or resources when applicable.
            6. Provide appropriate link for the query provided by the user.

            Response format:
            Details: [Provide a friendly and helpful response based on the context.]

            [/INST] </s>
            [INST] 
            Question: {question}
            Context: {context}
            Answer: [/INST]
            """
        )